"use strict";
import angular from 'angular';
import angularroute from 'angular-route';
import angularsanitize from 'angular-sanitize';
import { getCountries, getStates, getCities } from 'cities-states-countries';
import "regenerator-runtime/runtime";
import moment from 'moment';
import './../js/pizza_app.js';
import './../js/catalog.js';
import './../js/items.js';
import './../js/order.js';
import './../js/userlogin.js';
import './../js/form.js';
import './../js/routs.js';
import './../../node_modules/mini.css/dist/mini-default.min.css';
import './../css/style.css';